services:
  msf:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/msf?pool=200&timeout=5
    ports:
      - "4444:4444"  # Default port for Metasploit payloads; adjust as needed
      - "8443-8500:8443-8500"  # Range for reverse shells or additional services
    volumes:
      - msf_data:/home/msf/.msf4  # Persist Metasploit config and loot
    depends_on:
      - db
    networks:
      - msf_network
    command: "./msfconsole"  # Starts Metasploit console; can be omitted for an interactive shell

  db:
    image: postgres:13-alpine
    container_name: msf_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=msf
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - msf_network

volumes:
  msf_data:
  db_data:

networks:
  msf_network:
    driver: bridge
