services:
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      # Set the database URL so Metasploit knows how to connect to the Postgres container
      MSF_DATABASE_URL: postgresql://msf:msfpassword@db:5432/msf
    # Optionally, if you plan to use Metasploit’s web services or want to expose ports,
    # you can uncomment and adjust the following:
    # ports:
      - "3790:3790"

  db:
    image: postgres:12
    container_name: metasploit_db
    environment:
      POSTGRES_USER: msf
      POSTGRES_PASSWORD: msfpassword
      POSTGRES_DB: msf
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
